### ISSUE TITLE
Why do we need to run the preprocess_data from ATISS?

### ISSUE THREAD

**Issue by WenjiaWang0312** [weixi-feng/LayoutGPT#4]
Hi, there. Thank you for your wonderful work~ I am wondering why we need to process the 3D layout dataset. Since your method is training-free, we only need to sample the furniture from the 3D-FUTURE dataset and place them using the CSS code generated by your method. 😄

I am asking this for ATISS's buggy code of data processing.

**Comment by weixi-feng** [comment]
Hi! Thanks for the question. I haven't directly looked into the raw data in the 3D-FUTURE dataset. But my understanding is that 3D-FRONT contains scene information like room type and room size that is not available in 3D-FUTURE. Besides, the data processing code applies a bunch of filters to eliminate invalid scenes such as filtering out "unknown" furniture objects or extremely large/small rooms. So that's why we had to run data processing following ATISS. 

I might be wrong in this but I could look into the necessity of data processing shortly after.

**Comment by WenjiaWang0312** [comment]
Thank you for your response. I find that your generated room layouts are dumped into `.json`. While the render scripts in ATISS is based on `.pickle` file. How can I retrieve the furniture and arrange the scene from your `.json`?

**Comment by weixi-feng** [comment]
Retrieving and rendering furniture is achieved by ATISS. So we slightly modify their script to preprocess the data in our json files into a coherent format. You just need to follow [this section](https://github.com/weixi-feng/LayoutGPT#visualization) and the script will load our json files, preprocess the data, and visualize scene(s). But of course, you still need the pickle files from ATISS to run the script. 

Feel free to let me know if you have encountered problems and I will see what I can do. (Perhaps I can spend some time cleaning the code/instructions later)

**Comment by weixi-feng** [comment]
Hey Wenjia, 

Could you be specific on which query-id are you referring to? If it's the val_id used in run_layoutgpt_3d.py, then each id is used to get condition information like a room type and floor plan sizes from 3D-FRONT. These are standard inputs since we are doing conditional generation.
